### ISSUE TITLE
Proper HTTP headers + response to If-Modified-Sinse

### ISSUE THREAD

**Issue by spotman** [mmamedov/page-cache#1]
Hi there!

First of all, thank you so much for this awesome lib, It's very easy to use!
But I see that there is no proper HTTP headers like `Expires` and `Last-Modified` in response with cached file. I made some experiments locally and found that it's very easy to implement this coz we already know the expires interval and cache file modification time. Also it's possible to implement correct response for `If-Modified-Sinse` header with empty body and 304 status in case when cached file was not modified. These headers are very important for SE crawling bots and for proper HTTP caching.

I may make a PR for these improvements but I've never used a TDD and do not know is it possible to test these cases. What are you thinking about that?

**Comment by spotman** [comment]
@mmamedov I've created PR #2 for this issue, please review.

**Comment by mmamedov** [comment]
Hi @spotman ! Thanks for your contributions.

I agree with your points. Proper headers could be sent, but I think we should make it optional, possibly available in config. Because, some users might be dealing with headers on server level, and don't need PHP to do it.

As for clearing entire cache, I think it's not worthy to do it inside PHP - it will be slower than on OS  level (with lots of cache files and hash directories). Developer can do it manually using OS commands like `rm -rf`. 

I will look over the whole thing this weekend.

**Comment by spotman** [comment]
Hi, @mmamedov ! Thank you for quick response.

How is it possible to deal with these headers and 304 HTTP status on other levels? Web server does not know the cache file modification time, it does not know which cache file was used for current request, it does not know expires interval which may be vary between pages. I do not see any way to detect actual data for these headers in other places. Maybe I'm missing something? I may implement new config keys for enabling these headers but I do not understand the real use case when they would be used. 

I've selected PHP-way for clearing cache coz it is cross-platform and is working on Unix/Linux/Windows/Solaris/etc like a charm. `rm -rf` would work only in Unix/Linux and needs to be defined externally so you need to pass cache path to it and this would become a problem if you'll decide to change cache path. In this case you'll need to change it **twice**: in lib config and in external script, and this is unneeded dependency. Also not only developer needs to clear the cache, admin user may have web interface with a button for this. So it would be much better to call `PageCache` method than the external script in another language via `system` or `exec` call.

And my last argument is `consistency`. Your lib is all about HTTP request caching and it needs to have consistent API for controlling cache `inside`. Good software design involves [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle which recommends you to keep all data processing in one place. Trying to duplicate code/configs/data would always lead to problems in future. Keeping this in mind I've implemented proper HTTP headers handling and cache clearing inside your lib. I know that there are another ways to do it but all of them are `inconsistent`.

**Comment by mmamedov** [comment]
Hi @spotman,

Apache has a built-in functionality to issue Etags and Cache-control headers, along with several modules for cache control. You can also specify cache expiration for resources in .htaccess. When properly configured, Apache returns 304 header when browser sends back the Etag for unmodified content. There are other ways of handling cache directly from a web browser. Google itself has a lot of resources explainin this - https://developers.google.com/speed/docs/insights/LeverageBrowserCaching.

I also checked various popular websites for 304 headers on resources - very few actually use them.

I am personally using Apache's built-in modules along with .htaccess ExpiresByType for resources on Tmawto.com website that uses Page-Cache.

That all being said, I don't see why we couldn't implement our own PHP header sending mechanism, with having  it turned off by default (for backwards compatibility). 

I will merge your changes to my local branch, and modify code a little bit. This what I will try to do:
- Create a separate class for HTTP headers, write unit tests.
- Create config parameter for header output, and a method to set in on or off.
- Take your cache clearing logic, and put it inside FileSystem class. Hopefully write unit tests for that.

After all is done, I will push changes to master. At this point i'd want you to check it out too. If all looks good, I will tag it as a new version.

Thanks!

**Comment by spotman** [comment]
Hello, @mmamedov,

Thank you for detailed explanation, I have not used Apache for a few years and did not realized that you are using it for ETag caching. We are using Nginx + php-fpm and looking towards the Varnish as reverse proxy caching server coz it's much faster, but it requires the right HTTP headers set for proper request handling (that's why I've created this issue).

I accept your roadmap, it looks nice, and I'll help you with testing of new version.

As I understand you correctly, you execute ETag generating logic somewhere in your project's PHP code before calling PageCahe::init(). But PageCache does not generate ETag header when it's serving cached version and for better performance PageCache must be called before other request processing. My recomendation is to move ETag generation logic inside PageCache, coz this will allow us to use Apache/Nginx/Varnish caching by ETag which was generated from the real content, served by the PageCache even it was loaded from the cache file.

Also I have an idea to create adapter for storing cache in Memcached so our multi-server configuration would share the same page cache and it may be invalidated synchronously on all servers by one `PageCache::clearCache()` call from one server. I think that it may be done by introducing interface like `CacheStorageInterface` and moving storage logic from `Filesystem` to `CacheStorageFilesystem` + a lot of refactoring of current code + updating unittests. I may help with that if you'll find this idea acceptable.

Thank you for your attention! Have a nice day!

**Comment by mmamedov** [comment]
Hey @spotman,
I implemented headers. Will be committing now to master. I tested locally several times, and saw headers being set properly, overall logic worked well. 

Please also test it on your end. If all looks good, will tag as a new version.
If you have time, you could write unit tests for new HttpHeader class.

Once this issue is closed, we could start working on StorageInterface for Memcached.

**Comment by spotman** [comment]
Hi @mmamedov!

Thanks for your time and for giving attention to my issue. I need some time for reading docs about creating unittests coz it's new for me. 

I've tested your version and it's OK but there is side case that I had not realized before: the cache file `mtime` is not equal to the real page modification time. The problem is that all cache files has nearly the same `mtime` after cache clearing coz they are quickly regenerated under high load. So only the first page request has correct headers and this is confusing search engines coz they treat the page was changed but it wasn't.

I think we may get modification time from `Last-Modified` header captured right after cache file creating in `PageCache::createPage()` method (it can be done via PHP `headers_list` core function). I may implement new `HttpHeaders::getLastModifiedFromResponse` helper and change cache file mtime via `touch()` call inside of `Filesystem::setModificationTime()` only if headers are enabled.

Also I've noticed that `ETag` header value is calculating as sha1 from content. This is doing on every request, so it may create additional load, especially on the large pages. I suggest to calculate `ETag` as hash from `Last-Modified` date coz it must be relevant to content changes.

Both of these solutions require proper `Last-Modified` header to be sent from the app. If this can not be done, they wouldn't work correctly. We may omit processing if app hadn't set `Last-Modified` header, but we can do nothing if it was set and it is not correct. Btw, incorrect app headers would lead to the problems regardless of caching subsystem (php or apache or varnish) so maybe it is not a problem at all and we may rely on `headers_list()` in every case.

What do you think about that?

**Comment by mmamedov** [comment]
I agree with you on sha1_file 👍 , we need to get rid of that - why did I put it there in first place.

Since ETag has to be unique within a resource and not the entire domain, we can calculate it with md5() of last modified date of the file. Since we are not updating cache every second, we don't need to worry about microseconds and beyond. ETag based on files last modified time will be sufficient.
 
I didn't get your comment about high load, and time not being consistent. How does that affect us? Can you explain in more detail, maybe with code samples and values.

Thanks!

**Comment by spotman** [comment]
Ok, I'm glad that you've found useful the idea about `sha1_file`. But we need to fix the following collision before we switch to generating `ETag` from `Last-Modified` date.

- Let assume that we have a HTTP resource which was created (and last modified) at `12:00 on 1 January 2017`.
- At `14:00 on 1 January 2017` someone is requesting for this resource by HTTP.
- It is a new resource and there is no cache file for it so the `PageCache` waits for the request been processed by the app.
- The app is sending `Last-Modified` header with value of `12:00 on 1 January 2017`
- The `PageCache` creates the cache file with content and OS sets file modification time to `14:00 on 1 January 2017` (the time when the request was processed)
- At `15:00 on 1 January 2017` another user is requesting for this resource by HTTP.
- `PageCache` has a cache file for it so it's serving it to the client and sets `Last-Modified` header with value of `14:00 on 1 January 2017` (cache file `mtime`) and this is not correct coz the resource had not been modified after `12:00`.

It is not so bad for new resources coz the time diff is small. But assume we have a resource which was modified a year ago and today we had reset the whole `PageCache` cache. In this case all cache files for requested resources would have an `mtime` greater than the cache reset time. And for all of these resources we would have incorrect `Last-Modified` header values since `PageCache` relies on cache file `mtime`. So every HTTP client is fooled and required to download the "fresh" resource content which is actualy haven't changed. This also invalidate all cache in reverse proxy like Varnish (or Apache in your case). I think this is not the right behaviour.

That's why my suggestion is to detect original `Last-Modified` date from HTTP headers sent by the app and to synchronize cache file `mtime` with it. This way `Last-Modified` date will be correct and `ETag` header too.

BTW, I had read about unit testing of HTTP headers and found that the modern way of doing this is to use PSR-7 HTTP interfaces in `HttpHeaders` class or maybe in `PageCache` class too. This way we can simulate values of HTTP messages objects in unit tests without ugly parsing of the `headers_list` function result. This needs to make a lot of refactoring and it may be planned for future major version. Also implementing the PSR-7 HTTP messages will allow your library to be used as PSR-7 middleware in a lot of projects in the world. I think we may do this work in another branch and keep BC by creating default PSR-7 Request and Response implementation for using in `PageCache::init()` (or use something like https://github.com/zendframework/zend-diactoros). This will keep the library simple for current users and allow it to become the part of PHP7 world :)

```php
namespace PageCache;

class PageCache {

  private $request;
  private $response;

  public function init(ServerRequestInterface $request = null, ResponseInterface $response = null)
  {
    $this->request = $request ?: $this->getDefaultServerRequest();
    $this->response = $response ?: $this->getDefaultResponse();

   // current init code goes below
  }

  protected function getDefaultServerRequest()
  {
    return new \PageCache\PSR\DefaultServerRequest();
  }

  protected function getDefaultResponse()
  {
    return new \PageCache\PSR\DefaultResponse();
  }
}
```

**Comment by mmamedov** [comment]
I think we should not think in terms of HTTP resource, but in terms of page cache file. Then it becomes OK. I think no one should use a PHP caching solution to cache something for a year, they better create a script that dumps their content in HTML and server it from there, no PHP involved.

We can't know when a dynamic resource was last modified (you can't really tell when a PHP script that uses IO was last modified. unless you cache it and compare against cache). We can only think in terms of cache files - last modified date becomes the date of cache file. And also bear in mind that we override ETags and Last-modified caching by our internal expiration mechanism (setExpiration()).

You are right, major refactoring should not be in the scope of our current issue. And for unit tests you don't need to worry, I will take care of it. Thanks!

**Comment by spotman** [comment]
@mmamedov, my project has a lot of semi-static pages and my CMS can detect the real page modification time coz it can be combined from layout mtime and content mtime. The problem is not in case of caching document for one year but in case of one-year-old document becomes a document with "today" modification time after cache file regeneration. This leads to crawling budget leaking. [Google](https://support.google.com/webmasters/answer/35769) and [Yandex](https://yandex.com/support/webmaster/recommendations/indexing.xml) have concrete recommendations for the `Last-Modified` header coz it helps crawling bot to detect fresh documents and to crawl them first. After cache reset all documents become "new" and this is not OK for SEO. 

Anyway, I need to keep HTTP headers consistent in my project so I will implement this feature with an option to enable/disable it (disabled by default). After that I may create a PR and you may accept it or decline, up to you. Tell me please if you are interested in this PR.

Thank you for your attention.

**Comment by mmamedov** [comment]
@spotman Are you including those static pages in your PHP script, and running PageCache on top of that (I hope not)? Otherwise I can't think of a scenario where you need the "semi-static" page's last-mod-date. The whole idea is to cache content (store it in a file), and serve that file. Last-mod-date, ETag and any other time data will come of the that saved cache file. Obviously when that file expires (you define the expiration yourself), the new file will be generated and header data will also change accordingly.

Now, if you have pregenerated content youself, and saved it in bunch of static files, and simply want to include them - our headers will still be calculated based on the time of those files ($this->file). But we are not letting $this->file to be set externally. This could be something that could be implemented easily.

Do you have skype? It could be easier to discuss this in chat, instead of here.

**Comment by spotman** [comment]
@mmamedov I'm sorry for being late with the answer, it was a busy month.

I use Wordpress-like custom CMS, it is serving a lot of articles and guides. CMS can determine real content modification date clearly and it sends proper `Last-Modified` header. Every article must be indexed via search engines and so must have consistent HTTP headers. It is not my personal opinion but recommendation from Google and Yandex, it was proven by multiple A/B tests and years of SEO experience. If document was not changed it must not change `Last-Modified` and `ETag` headers. Period. If this rule is broken, then Google and Yandex can not determine real page content age and it leads to lowering this page crawling score and obviously incorrect dates in search result's snippet, etc. From this point of view it is very important to keep cache file `mtime` equal to app `Last-Modified` time. So clearing cache would not lead to incorrect HTTP headers and would not force Google to use crawling budget for scanning documents which was not really changed. This way new and really changed articles would be crawled fast without wasting the time for crawling unchanged articles with "fresh" `Last-Modified` time. It's very important for us coz we publish a lot of new articles every day and we have 1K+ articles total so making all articles with "today" `Last-Modified` time after cache reset is like SEO suicide for us.

I have some other task with higher priority for couple of weeks but I surely implement this function and create PR for you. If you want do discuss via Skype, please write your Skype login here or send it to my email `i.am [at] spotman.ru`. I'll be there ASAP. Thanks again for your support and help!

**Comment by mmamedov** [comment]
Merged changes into Master, includes:  
- General PSR-16 refactoring
- PageCache class is lighter now, no config params. All stored in `$this->config;`
- New Config class
- Updated all tests, added new ones.
- Updated Readme
- Updated all examples/demos.
- Updated format for config files
- Removed config-stub.php from src. Instead of maintaining 2 same files, I merged it into examples/config.php.

Let me know what you think. We can them make it a v.2.0, no backwards compatibility.

**Comment by spotman** [comment]
Everything seems to be OK, I've done tiny CS fixes and updated composer.json in PR #5 
There are some ideas about future improvements but we need to release these changes first.

**Comment by mmamedov** [comment]
I merged it looks good. I  just notices that we have 2 similar sections in Readme "Sending cache related HTTP headers" and "HTTP headers". Do you think you could merge it into a single section? If not I will do it, no problem.
I
 am also going to enable it on live Tmawto.com, will see how that goes. If all is OK, I think we can tag this as a v2.0

Thanks!

**Comment by mmamedov** [comment]
This has been done.
New v2.0 version is now available supporting these features.
I am closing the issue.
