### ISSUE TITLE
demo-headers.php return content for 304

### ISSUE THREAD

**Issue by mmamedov** [mmamedov/page-cache#15]
**Summary**
`demo-headers.php` used to work properly before, and not return any content when "304 Not Modified" was sent to client.

It's now sending content too, along with the header.

Investigate & fix.

**Comment by spotman** [comment]
Very strange... What page-cache version are you using: master or latest release?

**Comment by mmamedov** [comment]
Back then it was master. Latest release currently does it too on my local env.

**Comment by spotman** [comment]
OK, I'll check it right now.
