### ISSUE TITLE
How to include this class as standalone?

### ISSUE THREAD

**Issue by rotate4all** [mmamedov/page-cache#17]
Just for testing purposes and benchmarks I'd like to include this class into a project.
How to do that without composer? Thanks.

**Comment by mmamedov** [comment]
Hi,

To include any project without composer you need to require/load all
project files/classes manualy.

Why wouldn not you use composer? It will do it for you automatically, and
it is very easy to use and learn.

Best,
Muhammed

**Comment by rotate4all** [comment]
"file could not be downloaded: allow_url_fopen must be enabled in php.ini "... that's why.

**Comment by mmamedov** [comment]
You are having troubles installing composer?
Google it up to solve, you can pass arguments to php cli via -d flag, to
enable allow_.. flag to install composer.

**Comment by rotate4all** [comment]
Composer is installed. The error is shown when I try to install any package via composer.
Unfortunately that directive is disabled in php.ini for security reasons.
That's why I was asking for an alternative way to use your class.

**Comment by mmamedov** [comment]
If can not use composer, then you could manually download src/ directory
and manually require/include all classes in your project.
