### ISSUE TITLE
Refresh data if COOKIE changed

### ISSUE THREAD

**Issue by webserviceXXL** [mmamedov/page-cache#19]
Hi ho,

like described PageCache already detects $_SESSION changes and caches those pages correctly. Is there also a way to detect $_COOKIE changes?

Thanks!

**Comment by mmamedov** [comment]
Hi,

Yes.
You can design any Caching Strategy yourself and pass it to PageCache.
Below is the DefaultStrategy component. You need to create a new Strategy component, duplicate default one, and add any Cookie name you need to the end return statement.

https://github.com/mmamedov/page-cache/blob/master/src/Strategy/DefaultStrategy.php

Something like:

```       
 return md5($uri . $_SERVER['SCRIPT_NAME'] . $query . $session_str. $_COOKIE['myCookie']);
```

Based on that cookie parameter, PageCache will use a different key for the page.

**Comment by webserviceXXL** [comment]
Thanks!
