### ISSUE TITLE
getExpiresAt

### ISSUE THREAD

**Issue by elena-roman** [mmamedov/page-cache#4]
Hello,

We've update to the new version of this library, change the config file to the new version.
Since the update we starting getting the error below.  

PHP Fatal error: Call to a member function getExpiresAt() on integer in /srv/www/frontend/unity/vendor/mmamedov/page-cache/src/Storage/CacheItemStorage.php on line 123 

Can you please indicate a fix for this?

**Comment by mmamedov** [comment]
Hi,

Thanks for reporting this and using our library.

Could you provide more details on the error? What is your setup like?

Please do not use Master version yet, we are still working on it, it is not
stable yet. Once stable it will be released under v2.0 it will not be
backwards compatible.

Regards,
Muhammed

**Comment by mmamedov** [comment]
Hey @elena-roman,

We just introduced v2.0. Could you please upgrade to v2.0 and see if you still have that issue.

Thanks!
Muhammed
