### ISSUE TITLE
Clearing Cache

### ISSUE THREAD

**Issue by nomadicjosh** [mmamedov/page-cache#6]
How do you clear cache for a particular page on update?

**Comment by mmamedov** [comment]
Hi,

Simply call clearPageCache() method on that page.

**Comment by nomadicjosh** [comment]
So, I am using a framework. So if my layout is like this:

```
use PageCache\PageCache;
$cache = new PageCache();
$cache->config()->setCachePath(__DIR__ . '/cache/')
                ->setSendHeaders(true);
$cache->init();
?>
<html>
<body>
{contact_form}
</body>
</html>
```

do I need to call ```clearPageCache()``` after the form submits, or do I have to add ```clearPageCache()``` after ```</html>```?

**Comment by mmamedov** [comment]
If you need to clear cached page, you need to call it before init();

**Comment by nomadicjosh** [comment]
Ok, thanks.

**Comment by mmamedov** [comment]
You are welcome! Feel free to ask any questions you have.
