### ISSUE TITLE
User Login Form

### ISSUE THREAD

**Issue by emresaracoglu** [mmamedov/page-cache#7]
Hello,

You project is great, thank you. I have a question for user-login form. If the member tries to log in with the wrong information, he/she will encounter an error.

My codes is this:
```
if (isset($_POST['submit'])) {
        $emailAdresi = $_POST['email'];
	$password = $_POST['password']; 
	if ($user->login($emailAdresi, $password)) {
		$_SESSION['emailAdresi'] = $emailAdresi; 
			header('Location: ' . $SiteBaseAdresi . '/profile');
			exit;
		}
	} else {
		$error[] = $lang['HESAPWRONGUSERNAMEORPASSWORD']; 
	}
}
```
It does not show any errors with this form. The cache does not show any errors when it is active.
How can I overcome this problem?

Thank you.

**Comment by mmamedov** [comment]
Hi Emre,

It's not very clear from your code, but if you need sessions to be enabled for caching (for different session values, separate cache), then you will need to enable session support. Check out code in `examples/demo-session-support.php` .

That being said, I think it'd be better to disable cache on login/registration pages. There is no reason why you should use caching there, imho.

**Comment by emresaracoglu** [comment]
Absolutely, I gave up using the cache on the login and registration pages. It will be better this way
thank you for your time.
