### ISSUE TITLE
Clearing caches recursively

### ISSUE THREAD

**Issue by ali-imanpour** [mmamedov/page-cache#8]
I have urls patterns like below,
/{username}/{content_id}

When I want to clear cache for /{username} I want to clean cache the child urls of it.

example:
I
What's best solution?

**Comment by mmamedov** [comment]
Hi @isnaasharimam ,
Unfortunately there is no direct way of doing it in current version.

One quick dirty way would be to define all matching urls (i.e. an array) and hit those pages manually and calling `clearPageCache();` this would delete all cached versions of those pages.

I was planning on doing more features related to the management of cached resources. Your request seems an interesting scenario that I will be considering during implementation for sure.

Right now the cached item itself is generated by Caching Strategy  dynamically, w/o user interaction. The whole idea was to make it simple to use.
