### ISSUE TITLE
PSR-7 / PSR-15 support

### ISSUE THREAD

**Issue by spotman** [mmamedov/page-cache#9]
Hi there!

I hope you're doing well! What about implementing support for PSR-7 HTTP messages and PSR-15 middleware? I have some ideas about refactoring the core to support this standards right from the box, in the same manner like PSR-16 cache that we implemented last year. This will allow to use `page-cache` with modern applications and frameworks, including async processing in ReactPHP. The PHP is moving formward and we need to do so :)

Have a nice day!

**Comment by spotman** [comment]
@mmamedov ping

**Comment by mmamedov** [comment]
Hi Denis,

That’s a great idea, we could definetely try that.

We have another issue at the moment, for some reason on a very few
occasions I was getting a blank page. I’d like to focus on that first. It’d
be great if you also had time to go over the code to stabilize cache
serving.

Thanks!

**Comment by spotman** [comment]
@mmamedov OK, I have some spare time now and will try to debug this. Unfortunately, I had not this issue in my env so your PageCache initialization code is highly appreciated. I may emulate high load on this code and to check if everything is going well. Maybe we can create unit test for this case?

**Comment by mmamedov** [comment]
Yeah, makes sense.
We could try to cover that logic with more tests.
I used to run brianium parallel tests, but I think we disabled them because
of Travis issue.

**Comment by spotman** [comment]
We may write one test script based on `symfony/process` and run multiple instances of the PageCache with the same configuration. This will emulate concurrency and/or cache stampede. I think that capturing PSR response would be much cleaner than raw `echo` and `header` so we may test your test case and PSR messages implementation in one test suite. Also we may run these tests on a multiple set of configuration options so more use cases will be covered.
